require("core.config.smart-splits")
require("core.config.toggleterm")
require("core.config.theme")
require("core.config.better-escape")
require("core.config.comment")
require("core.config.treesitter")
require("core.config.bufferline")
require("core.config.lsp")
require("core.config.window-picker")
require("core.config.neo-tree")
require("core.config.formatter")
require("core.config.lualine")
require("core.config.session-manager")

vim.notify = require("notify")
