require("cvim.config.smart-splits")
require("cvim.config.toggleterm")
require("cvim.config.theme")
require("cvim.config.better-escape")
require("cvim.config.comment")
require("cvim.config.treesitter")
require("cvim.config.bufferline")
require("cvim.config.lsp")
require("cvim.config.window-picker")
require("cvim.config.neo-tree")
require("cvim.config.formatter")
require("cvim.config.lualine")
require("cvim.config.session-manager")
require("cvim.config.neoscroll")
require("cvim.config.autopairs")
require("cvim.config.cmp")
require("cvim.config.smoothcursor")
require("cvim.config.alpha")
require("cvim.config.zen-mode")
require("cvim.config.hop")
require("cvim.config.blankline")
require("cvim.config.dap")
require("cvim.config.deadcolumn")
require("cvim.config.navbuddy")

vim.notify = require("notify")
